name: Generate ABI

on:
  push:
    branches:
      - develop
      - cicd_exp
  workflow_dispatch:

permissions:
  contents: read


jobs:
  build:
    runs-on: self-hosted  # ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c  # v3.6.0
        with:
          node-version-file: package.json
      - id: npm-deps
        name: Install dependencies
        run: npm ci
      - id: abis
        name: Generate ABI files
        run: npm run build:abi
      - id: store-abis
        name: Store ABI files
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce  # v3.1.2
        with:
          name: ABIs
          path: abi/
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.4'
        env:
          HOME: ${{ runner.temp }}
      - id: abigen
        name: Build abigen
        env:
          HOME: ${{ runner.temp }}
        run: |
          go build -mod=mod -o abigen github.com/ethereum/go-ethereum/cmd/abigen
      - id: go-bindings
        name: Generate go bindings
        env:
          HOME: ${{ runner.temp }}
        run: |
          echo $HOME
          git clone git@github.com:momentum-xyz/go-contracts.git
          for FN in abi/*.json; do
            MNAME=`echo $FN| sed 's/abi\///;s/.json//'`
            LMNAME=`echo $MNAME| tr '[:upper:]' '[:lower:]'`
            echo $MNAME $LMNAME
            abigen --abi $FN --pkg abi --type $LMNAME --out $go-contracts/$LMNAME.go
          done
          ls go-contracts

