name: Pull request checks

on:
  pull_request:
    branched:
      - develop
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: self-hosted  # ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c  # v3.6.0
        with:
          node-version-file: package.json
      - id: npm-deps
        name: Install dependencies
        run: npm ci
      - id: test
        name: Test
        run: npm test
